### ISSUE TITLE
cURL error 60: SSL certificate problem:

### ISSUE THREAD

**Issue by IcaroRios** [bnbwebexpertise/laravel-google-cloud-print#2]
Hi, I'm with this problem:
"cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
I don't know what to do, please, help.

**Comment by gabsource** [comment]
It uses the Google Client. This kind of error indicates that your system does not have the CA certificates. See at https://github.com/google/google-api-php-client
