### ISSUE TITLE
Laravel Google cloud print with Zebra printer, can't get rid of left and right margins

### ISSUE THREAD

**Issue by FPMedia** [bnbwebexpertise/laravel-google-cloud-print#3]
When printing to a Zebra (GK420t) printer from Google Cloud Print (via Laravel plugins: SpringCS and bnbwebexpertise) the labels print about a 3rd of the width of the label with a margin on either side. 

I have tried: 
- All the CTJ options
- CSS styles (including @page) 
- Changing the settings on the printer utilities software (including print area and width) 
- Phoning Zebra

**Comment by gabsource** [comment]
Hi,

Can't do much to help you. All you can do is to pass CJT options via the `ticket()` method. The result depends on GCP engine.

If you are sending HTML, you can try to send PDF instead (built with the correct paper size) to prevent rendering issues with GCP engine.

**Comment by FPMedia** [comment]
HI,

Sorry for taking so long to respond, I appreciate you taking the time to reply :) Thank you, I have gone with your suggestion, just tweaking the options now. *hopeful*
