### ISSUE TITLE
Where do I find ticket options?

### ISSUE THREAD

**Issue by eriktobben** [bnbwebexpertise/laravel-google-cloud-print#4]
Hi,

Where do I find Printer ticket options? I have looked at https://developers.google.com/cloud-print/docs/cdd#cjt but I can not find the different options.

**Comment by gabsource** [comment]
Hi, all options are available on your linked page. Defined as protobuf. Use the variable names in snake case in the code.

Here some examples from the code at the root of the `PrintTicketSection` protobuf message :

From the `PageRangeTickeItem` protobuf message :

```php
      $this->ticket('page_range', [
            'interval' => [
                [
                    'start' => $start,
                    'end' => $end
                ]
            ]
        ]);
```
From the `MarginsTicketItem` protobuf message :

```php
        $this->ticket('margins', [
            'top_microns' => $top * 1000,
            'right_microns' => $right * 1000,
            'bottom_microns' => $bottom * 1000,
            'left_microns' => $left * 1000,
        ]);
```
