### ISSUE TITLE
Cant create service key account

### ISSUE THREAD

**Issue by ghost** [bnbwebexpertise/laravel-google-cloud-print#6]
Hi

  I´m losing my mind on this, i just can´t connect my laravel project to the printer, but if i go to the google cloud printer and print something directly from there it prints....I´m really confused about where to create the service account and what to put there, should i go to console.developers.google.com/apis or console.cloud.google.com? and then, when i´m create the service account it asks me for roles, whats that and what should i put there? could you please give me the steps to reproduce on how to do this?

Best Regards
  João

**Comment by gabsource** [comment]
Create the service account with the "Reader" (Project) role.
Then Add the service account email address to the printer to allow print.

Be aware of Google Cloud Print End-Of-Life this year : https://support.google.com/chrome/a/answer/9633006?hl=en
